version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
        - 80:80
    depends_on:
        - web
  web:
    build:
      context: .
    ports:
      - 3333:3333