# using Nginx base image
FROM nginx
# delete nginx default .conf .file
RUN rm /etc/nginx/conf.d/default.conf

# add the .conf file we have created
COPY default.conf /etc/nginx/conf.d/default.conf

#start the nginx server
CMD ["/usr/sbin/nginx", "-g", "daemon off;"]